name: credit_risk_modeling
channels:
  - conda-forge
  - defaults
dependencies:
  - feature_engine
  - imbalanced-learn>=0.11
  - ipython
  - jupyterlab
  - lightgbm
  - linearmodels
  - loguru
  - matplotlib
  - missingno
  - notebook
  - numpy<=1.24.3
  - pandas=1.5.3
  - pip
  - pytest=7.2.2
  - python=3.11
  - rust
  - scikit-learn>=1.3
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - typer
  - xgboost
  - pip:
      - -e .
      - fastapi
      - mkdocs
      - pyampute
      - python-dotenv
      - requests
      - uvicorn